print("Welcome, please select a select a song from this top 10 songs")
def fun():
    print("Dumdare Dumdare")
    print("Niddarani irisesei")
    print("Ooriki utharaana Dhaariki dakshanaana")
    print("Maguva Maguva")
    print("Last bench ro party symbol")
    print("rabbaru gajulu ")
    print("Nachore nachore")
    print("Amma amma")
    print("Ye kashtam yedhurocchina")
    print("Dani Kudi Bhujam Meedha Kadva")

while True:
    fun()    
    choice= input("Enter your song :").lower()
    if choice == "dumdare dumdare":
      print("""Dumdare Dumdare Dumdare Dumdare Dumda… Dumdare Dum Dumdare Dare Dum Dum Dum Ennenni Aashalu Adugaduguna EE College Lo Campus LoFightulu Coffee Shop Treatulu Saagele Saradhalalo EE Rojulu Friendship Kai Parugulu Dumdare Dumdare Dumdare Dumdare Dumda… Dumdare Dum Dumdare Dare Dum Dum Dum…. (Instrumental Music) One By Four La Kalisindi Sneham Canteen Chai la Attendance Thaggi Pokunda Undigaa Proxy Formulaa SUPERSTAR First Show Ki Maku Mass Bunk Manthram Undi Exams Lonaa Backlogs Valla Experience Enthentho Perigindhi.. One By Four La Kalisindi Sneham Canteen Chai la Attendance Thaggi Pokunda Undigaa Proxy Formulaa SUPERSTAR First Show Ki Maku Mass Bunk Manthram Undi Exams Lonaa Backlogs Valla Experience Enthentho Perigindhi.. Dumdare Dumdare Dumdare Dumdare Dumda… Dumdare Dum Dumdare Dare Dum Dum Dum…. (Instrumental Music) Ennenni Aashalu Adugaduguna EE College Lo Campus Lo Fightulu Coffee Shop Treatulu Ooooooo Meera…. Maa Andhari Kala Neevegaa Maa Yedhalo Neevegaa Branchullona Thedalu Unna Batch Okkatte… Machhaa Annaa Mamaa Annaa Friendship Okkate… Saadinchaalanundedo Heat Em Cheyyalo Doubt College Life Lo Chaduvu Lite Full Time Memu Kodathamu Le Sightu… Dumdare Dumdare Dumdare Dumdare Dumda… Dumdare Dum Dumdare Dare Dum Dum Dum…. """)
    elif choice == "niddarani irisesei":
         print("""Niddarani irisesei Reppalni therisaanu Nuvvocche dhaarullo Choopulni parisaanu Onteddu bandekki raara..Sagileti donkallo padilanga raara…Naligeti naa manasu Guruthocchi raa raa…Galaboti koorondi Pilichina raa raa Penimiti enni naallainadho..Ninu joosi kallaaraa…Ennenni nallainadhoNinu joosi kallaaraaChimmati cheekati Kammati sangatiYerraga kumpati Ecchaga duppatiKommallo sakkati Koyile okkati Kommallo sakkati Koyile okkatiGundene gonthu chesi Paadathandhi raa raa Penimiti Gundene gonthu chesi Paaduthandhiraa raa penimiti…(2) Polimera dhaati poyavani Polamaaripoye nee dhaaniniKodavali laanti ninnu Santi vaadini Konguna daasukune aali manasuni Soosi soodaka sulakana seyaku Naa thala raathalo Kalathalu raayaku Thaalibottu thalusukoni  """)
    elif choice == "ooriki utharaana Dhaariki dakshanaana":
        print("""Ooriki utharaana Dhaariki dakshanaana Ooriki utharaana Dhaariki dakshanaana Nee penimiti koolinaadamma Reddemma thalli Sakkanaina peddha reddemma Nalla regadi nelalona Yerra jonna chelalonaNee penimiti kaalinaadamma Reddemma thalli Gundelalasi poye kadhamma Sikke neeku sakkanamma Palavareni duvvenamma Sikke neeku sakkanamma Palavareni duvvenamma Sikku deesi koppe pettammaReddemma thalli Sindhuram bottu pettamma Kathi vadhara nethuramma Kadupu kaali poyenamma Kathi vadhara nethuramma Kadupu kaali poyenamma Kolichi ninnu vedinavamma Reddemma thalli Kachi mammu brovu maayammaNalla gudelo kodi koose Meda lona nidhura lese Nalla gudelo kodi koose Meda lona nidhura lese Sakkanaina peddha reddemma Bangaru thalli Sathyamaina peddha reddemma... Sathyamaina peddha reddemma...Sathyamaina peddha reddemma...""")
    elif choice == "maguva maguva":
        print("""Maguva Maguva, Lokaniki Telusa Nee Viluva, 0Maguva Maguva, Nee Sahananiki Sarihaddhulu Kalava, Atu Itu Anninta Nuve Jagamantha,Parugulu Theesthavu Inta Bayata,Alupani Ravantha Anane Anavanta,Velugulu Pusthavu Velle Dharantha,Maguva Maguva, Lokaniki Telusa Nee Viluva,Maguva Maguva, Nee Sahananiki Sarihaddhulu Kalava.Nee Katuka Kanulu Vipparakapothe.Ee Bhumiki Thelavaradhuga,Nee Gajula Cheyi Kadhaladakapothey,Ye Manugada Konasagadhuga,Prathi Varusaloni Premaga, Allukunna Bandhama,Anthuleni Nee Shrama, Anchanalakandhuna,Alayalu Korani, Adishakthi Roopama,Neevu Leni Jagathi Lo Deepame Veluguna,Needhagu Lalanalo Priyamagu Palanalo,Prathi Oka Magavadu Pasivadega,Endhari Pedhavulaloo Ye Chirunavunna,Aa Siri Perupulaku Moolam Nuvega,""")
    elif choice == "last bench ro party symbol":
        print("""Last bench ro party symbol-u Veseddam chalo wallu poster-uGeliche gang idi kaalarlettharoo Campus motthamu campaign cheyyaro Dong daga Daga ik daga ik daga Ding dongu Classroom lopale meeting pettaroo Prathi oka student-u gunde kollagottaroo Cigarette dammu break lona Kaaka canteenlo chayi thona Full to recharge ay modhaledadhaam hungamaDong daga Daga ik daga ik daga Ding dongu Votu veyadam only formality Thappaka gelusthundi mande party Chakram thippe sri krishna thodunte Anti kouravulu andhariki time bad yeDong daga Daga Ding donguu Ye petraa chinna cooling glassu Vachelopu breaking news Shirt button theesesi chesey lungi dance-uYe Kotra classu bunku Ready cheyara inku Challeskundham holi lekka Vachhesthunnay results eh All of you sing it once again Last bench ro party symbol-uVeseddam chalo wallu poster-u Geliche gang idi kaalarlettharoo Campus motthamu campaign cheyyaro Start ayindi re soundu aagadu Jai bolo krishnnanna jindhabad""")
    elif choice == "rabbaru gajulu":
        print("""rabbaru gajulu rabbaru gajulu rabbaru gajulu techane ribbanu puvvulu ribbanu puvvulu ribbanu puvvulu techane -2 ammani abbani athilidumani hah teri nee darikochane nuvvante padi padi nuvvante padi padi nuvvante padi padi chastane nee vente padi padi vastane nuvvante padi padi chastane nee vente padi padi vastane challani galini challani galini cheppina chotiki techaro.. venela gundelu venela gundelu vechani velaki patteyro.. thondara enduku thondara enduku thondara enduku vacheyro.. nuvvante padi padi nuvvante padi padi nuvvante padi padi chastaro.. nee vente padi padi vastaro.. nuvvante padi padi chastaro.. nee vente padi padi vastaro.. rajugari anugu meda ray ray rabba ray ray ray rabba ray ani vooregistane pilla o…. rani gari panpu meda dayi dayi amma dayi aay aay amma aay ani bajjopedatane pilla attagante ice avutana, itta chooste close avutana anta andanga alusautana dhi ani nuvvante, ee gurram ekkinchi joom ani jam ani chukkalu dikkulu chuttukostane |nuvvante| roju roju thotaku velli dhi dhi dhikum dhi dhi dhi dhikum dhiyya loveade dhame pilla dhi dhi dhikum dhi dhi dhi dhikum edo roju petaku velli pee pee dum dum pee pee pee dum dum ani pellade dhame pilla atta chepite settle ayipotha puste kadite jattayipota andulona bookayi potane aa.. aa.. ani nuvvante tali bottu techesta doom ani daam ani rubberu gajulu tagilinchestane """)
    elif choice == "nachore nachore":
        print("""Nachore nachore oo Yevadee gaja donga tega kakaloo teereena donga Yevadee dora donga darjaga dooreena donga Yevadee kasee donga kasee raseekata poseena donga Antha kalolamga anookoonde doche yama yama donga Nachore nachore oo Yevadee gaja donga tega kakaloo teereena donga Nachore nachore oo Yevadee dora donga darjaga dooreena donga donga Wana baby nowPedave kadeeleenchee madoovoo kooreepeenche Madheene mareegeechee needhoora tharaleenche Ek pal eeka pakee vastha Ek pal sega bakeeleestha Ek pal sookha sokhale thestha oh oh oh ohEk pal neenoo matadeestha\ Ek pal mohamatadeesthaEk pal seeree mootaloo veeppeestha tha tha tha tha Nachore nachore oo Yevadee gaja donga tega kakaloo teereena donga dongaYevadee dora donga darjaga dooreena donga donga Raseeka goona rama sarasa koola samaValapoo rana dheema modaloo pedadhama Deelbara porapatooothoonaDeelbara pareepatooothoona Deelbara chelee pataloo agena oh oh oh ohDeelbara tadabatooothoona Deelbara tadee batooothoona Deelbara veedeepodam jareegena dha dha dha Nachore nachore oo Yevadee gaja donga tega kakaloo teereena donga Yevadee dora donga darjaga dooreena donga Yevadee kasee donga kasee raseekata poseena donga Antha kalolamga anookoonde doche yama yama dongaNachore nachore oo Yevadee gaja donga tega kakaloo teereena donga Nachore nachore ooYevadee dora donga darjaga dooreena donga donga""")
    elif choice == "amma amma":
        print("""amma amma nee enga amma Unna vittaa enakkaaru amma Thedi paarthenae kaanom unna Kanna moochi yen? vaa nee velilaThaayae uyir pirindhaayae Enna thaniye thavikka vittaayae Indru nee paadum paaattukku Naan thoonga vendum Naan paadum paattukku Thaayae nee un kangal Thirandhalae podhum Amma amma nee enga amma Unna vittaa enakkaaru ammaNaan thoongum munnae Nee thoongi ponaai Thaayae en mel unnakkenna kovam Kannana kannae en dheiva pennae Kannil dhoosi neeoodhavendumAyyo yen indha saabam ellaamEndro naan seidha paavam Pagalum iravaagi bayamanadhae amma Vilakkin thunai indri irulaanadhae Uyirin oru paadhi pariponadhae amma Thanimai nilaiyaanadhae Amma amma nee enga amma Unna vittaa enakkaaru amma Naan pona pinnum nee vazha vendum Endhan moochu unnakullum undu Vaanengum vannam Poovellaam vaasam Naan vazhum ulagil dheivangal undu Nee enn perumayin ellai Undhan thandhai per sollum pillai Oorum peridhilai kalangaadhae En kannae Ulagam vilayaada Un kanmunnaeKaalam karaindhodumUn vazhvil karai serum Meendum naan un pillai  Amma amma nee enga amma Unna vittaa enakkaaru amma Enga ponaalum naanum varuven Kannaadi paaru naanum therivenThaayae uyir pirindhayae Kannae neyum enuyir thaanae Indru nee paadum paaattukku Naan thoonga vennum Naan paadum thaalaattu nee thoonga kadhoram endrendum ketkkum""")
    elif choice == "ye kashtam yedhurocchina":
        print("""ye kashtam yedhurocchina Kannelle yedhirinchina Aanandham ane uyyalalo nannu penchina Nannaku prematho Nannaku prematho Nannaku prematho ankitham Naa prathi kshanam Nenu ye dhaarilo vellinaYe addu Nannu aapina Nee venta nenu unnanani nannu nadipinchina Nannaku prematho Nannaku prematho Nannaku prematho ankitham Naa prathi kshanamYe thappu ne chesinaThappati adugule vesinaaOh chinni chirunavvuthone nannu manninchina Nannaku prematho Nannaku prematho Nannaku prematho ankitham Naa prathi kshanam Ye oosune cheppinaYe paatane paadinaBhale undhi malli paadara ani murisipoinaNannaku prematho Nannaku prematho Nannaku prematho ankitham Naa prathi kshanam Ee andhamaina rangula lokaana Oke janmalo vandhala janmalaku premandhinchina Nannaku prematho Nannaku prematho Nannaku prematho vandhanam ee paatatho Ee paatatho ee paatatho""")
    elif choice == "dani Kudi Bhujam Meedha Kadva ":
        print("""Dani Kudi Bhujam Meedha Kadva Dani Guttepu Raikulu Meriya Adhi Rammante Radhura Seliyaa Dani Pere Saranga Dariya Dani Edam Bhujam Meedha Kadva Dhani Yejentu Raikulu Meriya Adhi Rammante Radhura Seliyaa Dani Pere Saranga Dariya Kaalluku Vendi Gajjel Lekunna Nadiste Ghal Ghal Koppula Malle Dandal Lekunna Chekkili Gil Gil Navulo Levura Mutyaal Adhi Navite Vastay MuripalNotulo Sunam Kaasul Lekuna Thamala Paakul Muripantito Muripantito Muripantito Nokite Pedhavul Earaga Aithadhi-Ra Manadil Churiya Churiya Churiya Adhi Surma Pettil Churiya Adhi Ramante Radhura Seliya Dani Pere Saranga Dariya Dani Kudi Bhujam Meedha Kadva Dani Guttepu Raikulu Meriya Adhi Rammante Radhura Seliyaa Dani Pere Saranga Dariya Dani Edam Bhujam Meedha Kadva Dhani Yejentu Raikulu Meriya Adhi Rammante Radhura Seliyaa Dani Pere Saranga Dariya Rangeleni Naa Angi Jada Taakite Ayitadi Nallangi Maatala Ghatu Lawangi Marla Padite Adi Sivangi Teegalu Leni Saarangi Vaayinchabote Adi Firangi Gudiya Gudiya Gudiya Adi Chikki Chikkan Chidiya Adhi Ramante Radhura Seliya Dani Pere Saranga Dariya Dhani Sempal Ennala Kuriya Dhani Sevulaku Duddhul Meriya Adhi Ramante Radhura Seliya Dani Pere Saranga Dariya Dani Nadum Mudathale Meriya Padipothadi Mogola Duniya Adhi Ramante Radhura SeliyaDani Pere Saranga Dariya Dani Kudi Bhujam Meedha Kadva Dani Guttepu Raikulu Meriya Adhi Rammante Radhura Seliyaa Dani Pere Saranga Dariya Dani Edam Bhujam Meedha Kadva Dhani Yejentu Raikulu Meriya Adhi Rammante Radhura Seliyaa Dani Pere Saranga Dariya""")
    

    else:
        print("This is Invalid song")
        break
    var = input("Do you want another song type * \ quit:")
    if var == "*":
        continue
    elif var == "quit":
        break
